name: Front-End Deployment
  
on:
  push:
    branches:
      - master
    # workflow_run:
    #   workflows: ["Azure Web App Deployment"]
    #   types:
    #     - completed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
       node-version: '16.x'

    - name: Install dependencies and build
      run: |
       cd frontend
       npm install
       npm run build

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
       app-name: 'pipeline-test-git'
       publish-profile: ${{ secrets.AZURE_KEY }}
       package: 'frontend/build'